services:
  mongo_db:
    container_name: database_container
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017

  api:
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongo_db
    environment:
      - DATABASE_URL_MONGO=mongodb://mongo_db:27017/rbr
      - PORT=4000
    volumes:
      - ./:/usr/src/app

volumes:
  mongo_db: {}
  