services:
  mongo:
    container_name: db_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27020:27017

  # api:
  #   container_name: api_container
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27020

volumes:
  mongo_data: {}
  